import type { MissionDef } from '../types';
import { L } from '@/i18n/L';

/** Catálogo estático — pode vir de CMS/API depois */
export const MISSION_CATALOG: readonly MissionDef[] = [
  // —— Onboarding (uma vez) ——
  {
    id: 'onb_welcome',
    title: L('Bem-vindo ao OLEFOOT', 'Welcome to OLEFOOT'),
    description: L('Entre no app pela primeira vez.', 'Open the app for the first time.'),
    kind: 'onboarding',
    rewardExp: 8000,
    targetCount: 1,
    trackEvents: ['session_login'],
    minTier: 1,
  },
  {
    id: 'onb_home',
    title: L('Central de comando', 'Command centre'),
    description: L('Abra a tela Home.', 'Open the Home screen.'),
    kind: 'onboarding',
    rewardExp: 4000,
    targetCount: 1,
    trackEvents: ['screen_home'],
    minTier: 1,
  },
  {
    id: 'onb_team',
    title: L('Meu time', 'My team'),
    description: L('Visite Meu Time.', 'Visit My Team.'),
    kind: 'onboarding',
    rewardExp: 5000,
    targetCount: 1,
    trackEvents: ['screen_team'],
    minTier: 1,
  },
  {
    id: 'onb_wallet',
    title: L('Carteira OLE', 'OLE Wallet'),
    description: L('Abra a carteira BRO/OLE.', 'Open the BRO/OLE wallet.'),
    kind: 'onboarding',
    rewardExp: 5000,
    targetCount: 1,
    trackEvents: ['screen_wallet'],
    minTier: 1,
  },
  {
    id: 'onb_first_match',
    title: L('Estreia', 'Debut'),
    description: L('Dispute uma partida (ao vivo ou rápida).', 'Play a match (live or quick).'),
    kind: 'onboarding',
    rewardExp: 15000,
    targetCount: 1,
    trackEvents: ['match_completed', 'fast_match_completed'],
    trophy: {
      id: 'trophy_estreia',
      name: L('Troféu Estreia', 'Debut Trophy'),
      description: L('Primeira partida disputada no OLEFOOT.', 'First match played on OLEFOOT.'),
    },
    minTier: 1,
  },
  {
    id: 'onb_lineup',
    title: L('Titular definido', 'Starting XI set'),
    description: L('Salve a escalação titular.', 'Save your starting lineup.'),
    kind: 'onboarding',
    rewardExp: 10000,
    targetCount: 1,
    trackEvents: ['lineup_saved'],
    trophy: {
      id: 'trophy_titular',
      name: L('Troféu Titular', 'Starter Trophy'),
      description: L('Escalação titular registrada.', 'Starting lineup saved.'),
    },
    minTier: 1,
  },
  // —— Diárias ——
  {
    id: 'daily_login',
    title: L('Check-in diário', 'Daily check-in'),
    description: L('Entre no app hoje.', 'Open the app today.'),
    kind: 'daily',
    rewardExp: 3500,
    targetCount: 1,
    trackEvents: ['session_login'],
    minTier: 2,
  },
  {
    id: 'daily_match',
    title: L('Rodada do dia', 'Matchday'),
    description: L('Complete 1 partida.', 'Complete 1 match.'),
    kind: 'daily',
    rewardExp: 9000,
    targetCount: 1,
    trackEvents: ['match_completed', 'fast_match_completed'],
    minTier: 2,
  },
  {
    id: 'daily_goals',
    title: L('Artilharia', 'Goal rush'),
    description: L('Marque 2 gols no total (qualquer modo).', 'Score 2 goals in total (any mode).'),
    kind: 'daily',
    rewardExp: 7000,
    targetCount: 2,
    trackEvents: ['goal_scored'],
    minTier: 3,
  },
  {
    id: 'daily_explore',
    title: L('Olheiro', 'Scout'),
    description: L('Visite Transfer e Cidade no mesmo dia.', 'Visit Transfer and City on the same day.'),
    kind: 'daily',
    rewardExp: 5500,
    targetCount: 2,
    trackEvents: ['screen_transfer', 'screen_city'],
    progressMode: 'distinct',
    minTier: 3,
  },
  {
    id: 'daily_training',
    title: L('Ritmo de treino', 'Training rhythm'),
    description: L('Registre foco em treinos (tela Time).', 'Log training focus (Team screen).'),
    kind: 'daily',
    rewardExp: 4500,
    targetCount: 1,
    trackEvents: ['training_session'],
    minTier: 2,
  },
  // —— Semanais ——
  {
    id: 'weekly_matches',
    title: L('Temporada intensa', 'Busy season'),
    description: L('Complete 5 partidas na semana.', 'Complete 5 matches this week.'),
    kind: 'weekly',
    rewardExp: 28000,
    targetCount: 5,
    trackEvents: ['match_completed', 'fast_match_completed'],
    minTier: 4,
  },
  {
    id: 'weekly_wins',
    title: L('Vitórias que pesam', 'Wins that matter'),
    description: L('Vença 3 partidas.', 'Win 3 matches.'),
    kind: 'weekly',
    rewardExp: 32000,
    targetCount: 3,
    trackEvents: ['match_won'],
    minTier: 5,
  },
  {
    id: 'weekly_store',
    title: L('Mercado ativo', 'Active market'),
    description: L('Faça 1 compra na loja (OLE).', 'Make 1 store purchase (OLE).'),
    kind: 'weekly',
    rewardExp: 12000,
    targetCount: 1,
    trackEvents: ['store_purchase'],
    minTier: 2,
  },
  {
    id: 'weekly_missions',
    title: L('Gerente dedicado', 'Dedicated manager'),
    description: L('Resgate 8 missões (qualquer tipo) na semana.', 'Claim 8 missions (any type) this week.'),
    kind: 'weekly',
    rewardExp: 20000,
    targetCount: 8,
    trackEvents: ['mission_claimed'],
    minTier: 4,
  },
  // —— Conquistas (permanentes, uma vez) ——
  {
    id: 'ach_city',
    title: L('Dono da cidade', 'City owner'),
    description: L('Visite a visão Cidade 5 vezes (acumulado).', 'Visit the City view 5 times (total).'),
    kind: 'achievement',
    rewardExp: 20000,
    targetCount: 5,
    trackEvents: ['screen_city'],
    minTier: 3,
  },
  {
    id: 'ach_transfer',
    title: L('Olheiro profissional', 'Pro scout'),
    description: L('Abra o mercado 10 vezes (acumulado).', 'Open the market 10 times (total).'),
    kind: 'achievement',
    rewardExp: 25000,
    targetCount: 10,
    trackEvents: ['screen_transfer'],
    minTier: 4,
  },
  {
    id: 'ach_structure',
    title: L('Obras em andamento', 'Works in progress'),
    description: L('Evolua qualquer estrutura 3 vezes.', 'Upgrade any facility 3 times.'),
    kind: 'achievement',
    rewardExp: 40000,
    targetCount: 3,
    trackEvents: ['structure_upgraded'],
    trophy: {
      id: 'trophy_obras',
      name: L('Troféu Engenharia', 'Engineering Trophy'),
      description: L('Estrutura do clube em evolução.', 'Club facilities growing.'),
    },
    minTier: 5,
  },
  // —— Missões especiais (permanentes, troféu + alto EXP) ——
  {
    id: 'spec_ole_tour',
    title: L('Tour OLEFOOT', 'OLEFOOT Tour'),
    description: L('Visite Home, Meu Time, Wallet, Cidade e Transfer (uma vez cada).', 'Visit Home, My Team, Wallet, City and Transfer (once each).'),
    kind: 'special',
    rewardExp: 50000,
    targetCount: 5,
    trackEvents: ['screen_home', 'screen_team', 'screen_wallet', 'screen_city', 'screen_transfer'],
    progressMode: 'distinct',
    trophy: {
      id: 'trophy_tour',
      name: L('Troféu Tour Completo', 'Full Tour Trophy'),
      description: L('Conheceu todas as áreas principais do jogo.', 'Visited every main area of the game.'),
    },
    minTier: 6,
  },
  {
    id: 'spec_guerreiro',
    title: L('Guerreiro', 'Warrior'),
    description: L('Vença 10 partidas (vitórias registradas).', 'Win 10 matches (recorded wins).'),
    kind: 'special',
    rewardExp: 60000,
    targetCount: 10,
    trackEvents: ['match_won'],
    trophy: {
      id: 'trophy_guerreiro',
      name: L('Troféu Guerreiro', 'Warrior Trophy'),
      description: L('10 vitórias na carreira.', '10 career wins.'),
    },
    minTier: 7,
  },
  {
    id: 'spec_artilheiro',
    title: L('Artilheiro nato', 'Born scorer'),
    description: L('Marque 30 gols no total (qualquer modo).', 'Score 30 goals in total (any mode).'),
    kind: 'special',
    rewardExp: 55000,
    targetCount: 30,
    trackEvents: ['goal_scored'],
    trophy: {
      id: 'trophy_artilheiro',
      name: L('Troféu Artilheiro', 'Top Scorer Trophy'),
      description: L('30 gols marcados.', '30 goals scored.'),
    },
    minTier: 8,
  },
];

export const MISSION_BY_ID: ReadonlyMap<string, MissionDef> = new Map(
  MISSION_CATALOG.map((m) => [m.id, m])
);
