import type { MissionDef } from '../types';

/** Catálogo estático — pode vir de CMS/API depois */
export const MISSION_CATALOG: readonly MissionDef[] = [
  // —— Onboarding (uma vez) ——
  {
    id: 'onb_welcome',
    title: 'Bem-vindo ao OLEFOOT',
    description: 'Entre no app pela primeira vez.',
    kind: 'onboarding',
    rewardExp: 80,
    targetCount: 1,
    trackEvents: ['session_login'],
  },
  {
    id: 'onb_home',
    title: 'Central de comando',
    description: 'Abra a tela Home.',
    kind: 'onboarding',
    rewardExp: 40,
    targetCount: 1,
    trackEvents: ['screen_home'],
  },
  {
    id: 'onb_team',
    title: 'Meu time',
    description: 'Visite Meu Time.',
    kind: 'onboarding',
    rewardExp: 50,
    targetCount: 1,
    trackEvents: ['screen_team'],
  },
  {
    id: 'onb_wallet',
    title: 'Carteira OLE',
    description: 'Abra a carteira BRO/OLE.',
    kind: 'onboarding',
    rewardExp: 50,
    targetCount: 1,
    trackEvents: ['screen_wallet'],
  },
  {
    id: 'onb_first_match',
    title: 'Estreia',
    description: 'Dispute uma partida (ao vivo ou rápida).',
    kind: 'onboarding',
    rewardExp: 150,
    targetCount: 1,
    trackEvents: ['match_completed', 'fast_match_completed'],
    trophy: {
      id: 'trophy_estreia',
      name: 'Troféu Estreia',
      description: 'Primeira partida disputada no OLEFOOT.',
    },
  },
  {
    id: 'onb_lineup',
    title: 'Titular definido',
    description: 'Salve a escalação titular.',
    kind: 'onboarding',
    rewardExp: 100,
    targetCount: 1,
    trackEvents: ['lineup_saved'],
    trophy: {
      id: 'trophy_titular',
      name: 'Troféu Titular',
      description: 'Escalação titular registrada.',
    },
  },
  // —— Diárias ——
  {
    id: 'daily_login',
    title: 'Check-in diário',
    description: 'Entre no app hoje.',
    kind: 'daily',
    rewardExp: 35,
    targetCount: 1,
    trackEvents: ['session_login'],
  },
  {
    id: 'daily_match',
    title: 'Rodada do dia',
    description: 'Complete 1 partida.',
    kind: 'daily',
    rewardExp: 90,
    targetCount: 1,
    trackEvents: ['match_completed', 'fast_match_completed'],
  },
  {
    id: 'daily_goals',
    title: 'Artilharia',
    description: 'Marque 2 gols no total (qualquer modo).',
    kind: 'daily',
    rewardExp: 70,
    targetCount: 2,
    trackEvents: ['goal_scored'],
  },
  {
    id: 'daily_explore',
    title: 'Olheiro',
    description: 'Visite Transfer e Cidade no mesmo dia.',
    kind: 'daily',
    rewardExp: 55,
    targetCount: 2,
    trackEvents: ['screen_transfer', 'screen_city'],
    progressMode: 'distinct',
  },
  {
    id: 'daily_training',
    title: 'Ritmo de treino',
    description: 'Registre foco em treinos (tela Time).',
    kind: 'daily',
    rewardExp: 45,
    targetCount: 1,
    trackEvents: ['training_session'],
  },
  // —— Semanais ——
  {
    id: 'weekly_matches',
    title: 'Temporada intensa',
    description: 'Complete 5 partidas na semana.',
    kind: 'weekly',
    rewardExp: 280,
    targetCount: 5,
    trackEvents: ['match_completed', 'fast_match_completed'],
  },
  {
    id: 'weekly_wins',
    title: 'Vitórias que pesam',
    description: 'Vença 3 partidas.',
    kind: 'weekly',
    rewardExp: 320,
    targetCount: 3,
    trackEvents: ['match_won'],
  },
  {
    id: 'weekly_store',
    title: 'Mercado ativo',
    description: 'Faça 1 compra na loja (OLE).',
    kind: 'weekly',
    rewardExp: 120,
    targetCount: 1,
    trackEvents: ['store_purchase'],
  },
  {
    id: 'weekly_missions',
    title: 'Gerente dedicado',
    description: 'Resgate 8 missões (qualquer tipo) na semana.',
    kind: 'weekly',
    rewardExp: 200,
    targetCount: 8,
    trackEvents: ['mission_claimed'],
  },
  // —— Conquistas (permanentes, uma vez) ——
  {
    id: 'ach_city',
    title: 'Dono da cidade',
    description: 'Visite a visão Cidade 5 vezes (acumulado).',
    kind: 'achievement',
    rewardExp: 200,
    targetCount: 5,
    trackEvents: ['screen_city'],
  },
  {
    id: 'ach_transfer',
    title: 'Olheiro profissional',
    description: 'Abra o mercado 10 vezes (acumulado).',
    kind: 'achievement',
    rewardExp: 250,
    targetCount: 10,
    trackEvents: ['screen_transfer'],
  },
  {
    id: 'ach_structure',
    title: 'Obras em andamento',
    description: 'Evolua qualquer estrutura 3 vezes.',
    kind: 'achievement',
    rewardExp: 400,
    targetCount: 3,
    trackEvents: ['structure_upgraded'],
    trophy: {
      id: 'trophy_obras',
      name: 'Troféu Engenharia',
      description: 'Estrutura do clube em evolução.',
    },
  },
  // —— Missões especiais (permanentes, troféu + alto EXP) ——
  {
    id: 'spec_ole_tour',
    title: 'Tour OLEFOOT',
    description: 'Visite Home, Meu Time, Wallet, Cidade e Transfer (uma vez cada).',
    kind: 'special',
    rewardExp: 500,
    targetCount: 5,
    trackEvents: ['screen_home', 'screen_team', 'screen_wallet', 'screen_city', 'screen_transfer'],
    progressMode: 'distinct',
    trophy: {
      id: 'trophy_tour',
      name: 'Troféu Tour Completo',
      description: 'Conheceu todas as áreas principais do jogo.',
    },
  },
  {
    id: 'spec_guerreiro',
    title: 'Guerreiro',
    description: 'Vença 10 partidas (vitórias registradas).',
    kind: 'special',
    rewardExp: 600,
    targetCount: 10,
    trackEvents: ['match_won'],
    trophy: {
      id: 'trophy_guerreiro',
      name: 'Troféu Guerreiro',
      description: '10 vitórias na carreira.',
    },
  },
  {
    id: 'spec_artilheiro',
    title: 'Artilheiro nato',
    description: 'Marque 30 gols no total (qualquer modo).',
    kind: 'special',
    rewardExp: 550,
    targetCount: 30,
    trackEvents: ['goal_scored'],
    trophy: {
      id: 'trophy_artilheiro',
      name: 'Troféu Artilheiro',
      description: '30 gols marcados.',
    },
  },
];

export const MISSION_BY_ID: ReadonlyMap<string, MissionDef> = new Map(
  MISSION_CATALOG.map((m) => [m.id, m])
);
