import type { MissionDef } from '../types';

export const MISSION_CATALOG: MissionDef[] = [
  {
    id: 'onb_welcome',
    kind: 'onboarding',
    title: 'Bem-vindo',
    description: 'Abra o app uma vez.',
    targetCount: 1,
    rewardExp: 50,
    trackEvent: 'session_login',
  },
  {
    id: 'onb_home',
    kind: 'onboarding',
    title: 'Página inicial',
    description: 'Visite a Home.',
    targetCount: 1,
    rewardExp: 40,
    trackEvent: 'screen_home',
  },
  {
    id: 'daily_home',
    kind: 'daily',
    title: 'Rotina do dia',
    description: 'Abra a Home hoje.',
    targetCount: 1,
    rewardExp: 30,
    trackEvent: 'screen_home',
  },
  {
    id: 'daily_team',
    kind: 'daily',
    title: 'Olhar o elenco',
    description: 'Abra a tela Time.',
    targetCount: 1,
    rewardExp: 30,
    trackEvent: 'screen_team',
  },
  {
    id: 'daily_wallet',
    kind: 'daily',
    title: 'Finanças',
    description: 'Abra a carteira.',
    targetCount: 1,
    rewardExp: 25,
    trackEvent: 'screen_wallet',
  },
  {
    id: 'daily_city',
    kind: 'daily',
    title: 'Cidade',
    description: 'Abra a cidade.',
    targetCount: 1,
    rewardExp: 25,
    trackEvent: 'screen_city',
  },
  {
    id: 'daily_transfer',
    kind: 'daily',
    title: 'Mercado',
    description: 'Abra transferências.',
    targetCount: 1,
    rewardExp: 25,
    trackEvent: 'screen_transfer',
  },
  {
    id: 'daily_store',
    kind: 'daily',
    title: 'Loja',
    description: 'Abra a loja.',
    targetCount: 1,
    rewardExp: 25,
    trackEvent: 'screen_store',
  },
  {
    id: 'daily_missions_tab',
    kind: 'daily',
    title: 'Central de missões',
    description: 'Abra a aba Missões.',
    targetCount: 1,
    rewardExp: 20,
    trackEvent: 'screen_missions',
  },
  {
    id: 'weekly_missions',
    kind: 'weekly',
    title: 'Compromisso semanal',
    description: 'Resgate 3 missões (qualquer) nesta semana.',
    targetCount: 3,
    rewardExp: 200,
    trackEvent: 'mission_claimed',
  },
  {
    id: 'ach_first_win',
    kind: 'achievement',
    title: 'Primeira vitória',
    description: 'Vença uma partida.',
    targetCount: 1,
    rewardExp: 100,
    trackEvent: 'match_won',
  },
  {
    id: 'ach_goals',
    kind: 'achievement',
    title: 'Artilheiro',
    description: 'Marque 3 gols (acumulado).',
    targetCount: 3,
    rewardExp: 150,
    trackEvent: 'goal_scored',
  },
  {
    id: 'ach_matches',
    kind: 'achievement',
    title: 'Rodada completa',
    description: 'Termine 2 partidas.',
    targetCount: 2,
    rewardExp: 120,
    trackEvent: 'match_completed',
  },
];
